package cn.com.gps169.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class DailyStat {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.daily_stat_id
     *
     * @mbggenerated
     */
    private Integer dailyStatId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.vehicle_id
     *
     * @mbggenerated
     */
    private Integer vehicleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.occur_date
     *
     * @mbggenerated
     */
    private Integer occurDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.fuel_amount
     *
     * @mbggenerated
     */
    private BigDecimal fuelAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.mileage
     *
     * @mbggenerated
     */
    private BigDecimal mileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.refuel
     *
     * @mbggenerated
     */
    private BigDecimal refuel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.fuel_incount
     *
     * @mbggenerated
     */
    private BigDecimal fuelIncount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.mileage_incount
     *
     * @mbggenerated
     */
    private BigDecimal mileageIncount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.fuel_per_100km
     *
     * @mbggenerated
     */
    private BigDecimal fuelPer100km;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.fee_per_100km
     *
     * @mbggenerated
     */
    private BigDecimal feePer100km;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_daily_stat.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.daily_stat_id
     *
     * @return the value of gps_daily_stat.daily_stat_id
     *
     * @mbggenerated
     */
    public Integer getDailyStatId() {
        return dailyStatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.daily_stat_id
     *
     * @param dailyStatId the value for gps_daily_stat.daily_stat_id
     *
     * @mbggenerated
     */
    public void setDailyStatId(Integer dailyStatId) {
        this.dailyStatId = dailyStatId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.vehicle_id
     *
     * @return the value of gps_daily_stat.vehicle_id
     *
     * @mbggenerated
     */
    public Integer getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.vehicle_id
     *
     * @param vehicleId the value for gps_daily_stat.vehicle_id
     *
     * @mbggenerated
     */
    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.occur_date
     *
     * @return the value of gps_daily_stat.occur_date
     *
     * @mbggenerated
     */
    public Integer getOccurDate() {
        return occurDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.occur_date
     *
     * @param occurDate the value for gps_daily_stat.occur_date
     *
     * @mbggenerated
     */
    public void setOccurDate(Integer occurDate) {
        this.occurDate = occurDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.fuel_amount
     *
     * @return the value of gps_daily_stat.fuel_amount
     *
     * @mbggenerated
     */
    public BigDecimal getFuelAmount() {
        return fuelAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.fuel_amount
     *
     * @param fuelAmount the value for gps_daily_stat.fuel_amount
     *
     * @mbggenerated
     */
    public void setFuelAmount(BigDecimal fuelAmount) {
        this.fuelAmount = fuelAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.mileage
     *
     * @return the value of gps_daily_stat.mileage
     *
     * @mbggenerated
     */
    public BigDecimal getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.mileage
     *
     * @param mileage the value for gps_daily_stat.mileage
     *
     * @mbggenerated
     */
    public void setMileage(BigDecimal mileage) {
        this.mileage = mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.refuel
     *
     * @return the value of gps_daily_stat.refuel
     *
     * @mbggenerated
     */
    public BigDecimal getRefuel() {
        return refuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.refuel
     *
     * @param refuel the value for gps_daily_stat.refuel
     *
     * @mbggenerated
     */
    public void setRefuel(BigDecimal refuel) {
        this.refuel = refuel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.fuel_incount
     *
     * @return the value of gps_daily_stat.fuel_incount
     *
     * @mbggenerated
     */
    public BigDecimal getFuelIncount() {
        return fuelIncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.fuel_incount
     *
     * @param fuelIncount the value for gps_daily_stat.fuel_incount
     *
     * @mbggenerated
     */
    public void setFuelIncount(BigDecimal fuelIncount) {
        this.fuelIncount = fuelIncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.mileage_incount
     *
     * @return the value of gps_daily_stat.mileage_incount
     *
     * @mbggenerated
     */
    public BigDecimal getMileageIncount() {
        return mileageIncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.mileage_incount
     *
     * @param mileageIncount the value for gps_daily_stat.mileage_incount
     *
     * @mbggenerated
     */
    public void setMileageIncount(BigDecimal mileageIncount) {
        this.mileageIncount = mileageIncount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.fuel_per_100km
     *
     * @return the value of gps_daily_stat.fuel_per_100km
     *
     * @mbggenerated
     */
    public BigDecimal getFuelPer100km() {
        return fuelPer100km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.fuel_per_100km
     *
     * @param fuelPer100km the value for gps_daily_stat.fuel_per_100km
     *
     * @mbggenerated
     */
    public void setFuelPer100km(BigDecimal fuelPer100km) {
        this.fuelPer100km = fuelPer100km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.fee_per_100km
     *
     * @return the value of gps_daily_stat.fee_per_100km
     *
     * @mbggenerated
     */
    public BigDecimal getFeePer100km() {
        return feePer100km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.fee_per_100km
     *
     * @param feePer100km the value for gps_daily_stat.fee_per_100km
     *
     * @mbggenerated
     */
    public void setFeePer100km(BigDecimal feePer100km) {
        this.feePer100km = feePer100km;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_daily_stat.created
     *
     * @return the value of gps_daily_stat.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_daily_stat.created
     *
     * @param created the value for gps_daily_stat.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_daily_stat
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DailyStat other = (DailyStat) that;
        return (this.getDailyStatId() == null ? other.getDailyStatId() == null : this.getDailyStatId().equals(other.getDailyStatId()))
            && (this.getVehicleId() == null ? other.getVehicleId() == null : this.getVehicleId().equals(other.getVehicleId()))
            && (this.getOccurDate() == null ? other.getOccurDate() == null : this.getOccurDate().equals(other.getOccurDate()))
            && (this.getFuelAmount() == null ? other.getFuelAmount() == null : this.getFuelAmount().equals(other.getFuelAmount()))
            && (this.getMileage() == null ? other.getMileage() == null : this.getMileage().equals(other.getMileage()))
            && (this.getRefuel() == null ? other.getRefuel() == null : this.getRefuel().equals(other.getRefuel()))
            && (this.getFuelIncount() == null ? other.getFuelIncount() == null : this.getFuelIncount().equals(other.getFuelIncount()))
            && (this.getMileageIncount() == null ? other.getMileageIncount() == null : this.getMileageIncount().equals(other.getMileageIncount()))
            && (this.getFuelPer100km() == null ? other.getFuelPer100km() == null : this.getFuelPer100km().equals(other.getFuelPer100km()))
            && (this.getFeePer100km() == null ? other.getFeePer100km() == null : this.getFeePer100km().equals(other.getFeePer100km()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_daily_stat
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDailyStatId() == null) ? 0 : getDailyStatId().hashCode());
        result = prime * result + ((getVehicleId() == null) ? 0 : getVehicleId().hashCode());
        result = prime * result + ((getOccurDate() == null) ? 0 : getOccurDate().hashCode());
        result = prime * result + ((getFuelAmount() == null) ? 0 : getFuelAmount().hashCode());
        result = prime * result + ((getMileage() == null) ? 0 : getMileage().hashCode());
        result = prime * result + ((getRefuel() == null) ? 0 : getRefuel().hashCode());
        result = prime * result + ((getFuelIncount() == null) ? 0 : getFuelIncount().hashCode());
        result = prime * result + ((getMileageIncount() == null) ? 0 : getMileageIncount().hashCode());
        result = prime * result + ((getFuelPer100km() == null) ? 0 : getFuelPer100km().hashCode());
        result = prime * result + ((getFeePer100km() == null) ? 0 : getFeePer100km().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        return result;
    }
}