package cn.com.gps169.db.model;

import java.math.BigDecimal;
import java.util.Date;

public class Refuel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_refuel.refuel_id
     *
     * @mbggenerated
     */
    private Integer refuelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_refuel.vehicle_id
     *
     * @mbggenerated
     */
    private Integer vehicleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_refuel.refuel_amount
     *
     * @mbggenerated
     */
    private BigDecimal refuelAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_refuel.fuel_amount
     *
     * @mbggenerated
     */
    private BigDecimal fuelAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_refuel.mileage
     *
     * @mbggenerated
     */
    private BigDecimal mileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_refuel.refuel_date
     *
     * @mbggenerated
     */
    private Date refuelDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_refuel.location
     *
     * @mbggenerated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gps_refuel.created
     *
     * @mbggenerated
     */
    private Date created;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_refuel.refuel_id
     *
     * @return the value of gps_refuel.refuel_id
     *
     * @mbggenerated
     */
    public Integer getRefuelId() {
        return refuelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_refuel.refuel_id
     *
     * @param refuelId the value for gps_refuel.refuel_id
     *
     * @mbggenerated
     */
    public void setRefuelId(Integer refuelId) {
        this.refuelId = refuelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_refuel.vehicle_id
     *
     * @return the value of gps_refuel.vehicle_id
     *
     * @mbggenerated
     */
    public Integer getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_refuel.vehicle_id
     *
     * @param vehicleId the value for gps_refuel.vehicle_id
     *
     * @mbggenerated
     */
    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_refuel.refuel_amount
     *
     * @return the value of gps_refuel.refuel_amount
     *
     * @mbggenerated
     */
    public BigDecimal getRefuelAmount() {
        return refuelAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_refuel.refuel_amount
     *
     * @param refuelAmount the value for gps_refuel.refuel_amount
     *
     * @mbggenerated
     */
    public void setRefuelAmount(BigDecimal refuelAmount) {
        this.refuelAmount = refuelAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_refuel.fuel_amount
     *
     * @return the value of gps_refuel.fuel_amount
     *
     * @mbggenerated
     */
    public BigDecimal getFuelAmount() {
        return fuelAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_refuel.fuel_amount
     *
     * @param fuelAmount the value for gps_refuel.fuel_amount
     *
     * @mbggenerated
     */
    public void setFuelAmount(BigDecimal fuelAmount) {
        this.fuelAmount = fuelAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_refuel.mileage
     *
     * @return the value of gps_refuel.mileage
     *
     * @mbggenerated
     */
    public BigDecimal getMileage() {
        return mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_refuel.mileage
     *
     * @param mileage the value for gps_refuel.mileage
     *
     * @mbggenerated
     */
    public void setMileage(BigDecimal mileage) {
        this.mileage = mileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_refuel.refuel_date
     *
     * @return the value of gps_refuel.refuel_date
     *
     * @mbggenerated
     */
    public Date getRefuelDate() {
        return refuelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_refuel.refuel_date
     *
     * @param refuelDate the value for gps_refuel.refuel_date
     *
     * @mbggenerated
     */
    public void setRefuelDate(Date refuelDate) {
        this.refuelDate = refuelDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_refuel.location
     *
     * @return the value of gps_refuel.location
     *
     * @mbggenerated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_refuel.location
     *
     * @param location the value for gps_refuel.location
     *
     * @mbggenerated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gps_refuel.created
     *
     * @return the value of gps_refuel.created
     *
     * @mbggenerated
     */
    public Date getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gps_refuel.created
     *
     * @param created the value for gps_refuel.created
     *
     * @mbggenerated
     */
    public void setCreated(Date created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Refuel other = (Refuel) that;
        return (this.getRefuelId() == null ? other.getRefuelId() == null : this.getRefuelId().equals(other.getRefuelId()))
            && (this.getVehicleId() == null ? other.getVehicleId() == null : this.getVehicleId().equals(other.getVehicleId()))
            && (this.getRefuelAmount() == null ? other.getRefuelAmount() == null : this.getRefuelAmount().equals(other.getRefuelAmount()))
            && (this.getFuelAmount() == null ? other.getFuelAmount() == null : this.getFuelAmount().equals(other.getFuelAmount()))
            && (this.getMileage() == null ? other.getMileage() == null : this.getMileage().equals(other.getMileage()))
            && (this.getRefuelDate() == null ? other.getRefuelDate() == null : this.getRefuelDate().equals(other.getRefuelDate()))
            && (this.getLocation() == null ? other.getLocation() == null : this.getLocation().equals(other.getLocation()))
            && (this.getCreated() == null ? other.getCreated() == null : this.getCreated().equals(other.getCreated()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRefuelId() == null) ? 0 : getRefuelId().hashCode());
        result = prime * result + ((getVehicleId() == null) ? 0 : getVehicleId().hashCode());
        result = prime * result + ((getRefuelAmount() == null) ? 0 : getRefuelAmount().hashCode());
        result = prime * result + ((getFuelAmount() == null) ? 0 : getFuelAmount().hashCode());
        result = prime * result + ((getMileage() == null) ? 0 : getMileage().hashCode());
        result = prime * result + ((getRefuelDate() == null) ? 0 : getRefuelDate().hashCode());
        result = prime * result + ((getLocation() == null) ? 0 : getLocation().hashCode());
        result = prime * result + ((getCreated() == null) ? 0 : getCreated().hashCode());
        return result;
    }
}