package cn.com.gps169.db.model;

import java.util.Date;

public class VehicleTask {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_task.task_id
     *
     * @mbggenerated
     */
    private Integer taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_task.vehicle_id
     *
     * @mbggenerated
     */
    private Integer vehicleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_task.route
     *
     * @mbggenerated
     */
    private String route;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_task.route_mileage
     *
     * @mbggenerated
     */
    private String routeMileage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_task.created_time
     *
     * @mbggenerated
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vehicle_task.route_detail
     *
     * @mbggenerated
     */
    private byte[] routeDetail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_task.task_id
     *
     * @return the value of vehicle_task.task_id
     *
     * @mbggenerated
     */
    public Integer getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_task.task_id
     *
     * @param taskId the value for vehicle_task.task_id
     *
     * @mbggenerated
     */
    public void setTaskId(Integer taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_task.vehicle_id
     *
     * @return the value of vehicle_task.vehicle_id
     *
     * @mbggenerated
     */
    public Integer getVehicleId() {
        return vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_task.vehicle_id
     *
     * @param vehicleId the value for vehicle_task.vehicle_id
     *
     * @mbggenerated
     */
    public void setVehicleId(Integer vehicleId) {
        this.vehicleId = vehicleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_task.route
     *
     * @return the value of vehicle_task.route
     *
     * @mbggenerated
     */
    public String getRoute() {
        return route;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_task.route
     *
     * @param route the value for vehicle_task.route
     *
     * @mbggenerated
     */
    public void setRoute(String route) {
        this.route = route == null ? null : route.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_task.route_mileage
     *
     * @return the value of vehicle_task.route_mileage
     *
     * @mbggenerated
     */
    public String getRouteMileage() {
        return routeMileage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_task.route_mileage
     *
     * @param routeMileage the value for vehicle_task.route_mileage
     *
     * @mbggenerated
     */
    public void setRouteMileage(String routeMileage) {
        this.routeMileage = routeMileage == null ? null : routeMileage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_task.created_time
     *
     * @return the value of vehicle_task.created_time
     *
     * @mbggenerated
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_task.created_time
     *
     * @param createdTime the value for vehicle_task.created_time
     *
     * @mbggenerated
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vehicle_task.route_detail
     *
     * @return the value of vehicle_task.route_detail
     *
     * @mbggenerated
     */
    public byte[] getRouteDetail() {
        return routeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vehicle_task.route_detail
     *
     * @param routeDetail the value for vehicle_task.route_detail
     *
     * @mbggenerated
     */
    public void setRouteDetail(byte[] routeDetail) {
        this.routeDetail = routeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_task
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        VehicleTask other = (VehicleTask) that;
        return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getVehicleId() == null ? other.getVehicleId() == null : this.getVehicleId().equals(other.getVehicleId()))
            && (this.getRoute() == null ? other.getRoute() == null : this.getRoute().equals(other.getRoute()))
            && (this.getRouteMileage() == null ? other.getRouteMileage() == null : this.getRouteMileage().equals(other.getRouteMileage()))
            && (this.getCreatedTime() == null ? other.getCreatedTime() == null : this.getCreatedTime().equals(other.getCreatedTime()))
            && (this.getRouteDetail() == null ? other.getRouteDetail() == null : this.getRouteDetail().equals(other.getRouteDetail()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vehicle_task
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getVehicleId() == null) ? 0 : getVehicleId().hashCode());
        result = prime * result + ((getRoute() == null) ? 0 : getRoute().hashCode());
        result = prime * result + ((getRouteMileage() == null) ? 0 : getRouteMileage().hashCode());
        result = prime * result + ((getCreatedTime() == null) ? 0 : getCreatedTime().hashCode());
        result = prime * result + ((getRouteDetail() == null) ? 0 : getRouteDetail().hashCode());
        return result;
    }
}