package cn.com.gps169.db.dao;

import cn.com.gps169.db.model.Refuel;
import cn.com.gps169.db.model.RefuelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RefuelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    int countByExample(RefuelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    int deleteByExample(RefuelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer refuelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    int insert(Refuel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    int insertSelective(Refuel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    List<Refuel> selectByExample(RefuelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    Refuel selectByPrimaryKey(Integer refuelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Refuel record, @Param("example") RefuelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Refuel record, @Param("example") RefuelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Refuel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_refuel
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Refuel record);
}