package cn.com.gps169.db.dao;

import cn.com.gps169.db.model.TerminalVehicle;
import cn.com.gps169.db.model.TerminalVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TerminalVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    int countByExample(TerminalVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    int deleteByExample(TerminalVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer terminalVehiclesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    int insert(TerminalVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    int insertSelective(TerminalVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    List<TerminalVehicle> selectByExample(TerminalVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    TerminalVehicle selectByPrimaryKey(Integer terminalVehiclesId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TerminalVehicle record, @Param("example") TerminalVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TerminalVehicle record, @Param("example") TerminalVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TerminalVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gps_terminal_vehicles
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TerminalVehicle record);
}