package cn.com.gps169.db.dao;

import cn.com.gps169.db.model.UserVehicle;
import cn.com.gps169.db.model.UserVehicleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserVehicleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    int countByExample(UserVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    int deleteByExample(UserVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    int insert(UserVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    int insertSelective(UserVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    List<UserVehicle> selectByExample(UserVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    UserVehicle selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserVehicle record, @Param("example") UserVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserVehicle record, @Param("example") UserVehicleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserVehicle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_vehicle
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserVehicle record);
}