// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/vehiclePb.proto

package cn.com.gps169.common.pb;

public final class VehiclePb {
  private VehiclePb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class Vehicle extends
      com.google.protobuf.GeneratedMessage {
    // Use Vehicle.newBuilder() to construct.
    private Vehicle() {
      initFields();
    }
    private Vehicle(boolean noInit) {}
    
    private static final Vehicle defaultInstance;
    public static Vehicle getDefaultInstance() {
      return defaultInstance;
    }
    
    public Vehicle getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.gps169.common.pb.VehiclePb.internal_static_Vehicle_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.gps169.common.pb.VehiclePb.internal_static_Vehicle_fieldAccessorTable;
    }
    
    // required int32 vehicleId = 1;
    public static final int VEHICLEID_FIELD_NUMBER = 1;
    private boolean hasVehicleId;
    private int vehicleId_ = 0;
    public boolean hasVehicleId() { return hasVehicleId; }
    public int getVehicleId() { return vehicleId_; }
    
    // required string plateNo = 2;
    public static final int PLATENO_FIELD_NUMBER = 2;
    private boolean hasPlateNo;
    private java.lang.String plateNo_ = "";
    public boolean hasPlateNo() { return hasPlateNo; }
    public java.lang.String getPlateNo() { return plateNo_; }
    
    // required string vin = 3;
    public static final int VIN_FIELD_NUMBER = 3;
    private boolean hasVin;
    private java.lang.String vin_ = "";
    public boolean hasVin() { return hasVin; }
    public java.lang.String getVin() { return vin_; }
    
    // required string ein = 4;
    public static final int EIN_FIELD_NUMBER = 4;
    private boolean hasEin;
    private java.lang.String ein_ = "";
    public boolean hasEin() { return hasEin; }
    public java.lang.String getEin() { return ein_; }
    
    // required string simNo = 5;
    public static final int SIMNO_FIELD_NUMBER = 5;
    private boolean hasSimNo;
    private java.lang.String simNo_ = "";
    public boolean hasSimNo() { return hasSimNo; }
    public java.lang.String getSimNo() { return simNo_; }
    
    // required string terminalNo = 6;
    public static final int TERMINALNO_FIELD_NUMBER = 6;
    private boolean hasTerminalNo;
    private java.lang.String terminalNo_ = "";
    public boolean hasTerminalNo() { return hasTerminalNo; }
    public java.lang.String getTerminalNo() { return terminalNo_; }
    
    // required int32 terminalFlag = 7;
    public static final int TERMINALFLAG_FIELD_NUMBER = 7;
    private boolean hasTerminalFlag;
    private int terminalFlag_ = 0;
    public boolean hasTerminalFlag() { return hasTerminalFlag; }
    public int getTerminalFlag() { return terminalFlag_; }
    
    // required int32 terminal_status = 8;
    public static final int TERMINAL_STATUS_FIELD_NUMBER = 8;
    private boolean hasTerminalStatus;
    private int terminalStatus_ = 0;
    public boolean hasTerminalStatus() { return hasTerminalStatus; }
    public int getTerminalStatus() { return terminalStatus_; }
    
    // required string serviceStartTime = 9;
    public static final int SERVICESTARTTIME_FIELD_NUMBER = 9;
    private boolean hasServiceStartTime;
    private java.lang.String serviceStartTime_ = "";
    public boolean hasServiceStartTime() { return hasServiceStartTime; }
    public java.lang.String getServiceStartTime() { return serviceStartTime_; }
    
    // required string serviceEndTime = 10;
    public static final int SERVICEENDTIME_FIELD_NUMBER = 10;
    private boolean hasServiceEndTime;
    private java.lang.String serviceEndTime_ = "";
    public boolean hasServiceEndTime() { return hasServiceEndTime; }
    public java.lang.String getServiceEndTime() { return serviceEndTime_; }
    
    // required int32 fleeStatus = 11;
    public static final int FLEESTATUS_FIELD_NUMBER = 11;
    private boolean hasFleeStatus;
    private int fleeStatus_ = 0;
    public boolean hasFleeStatus() { return hasFleeStatus; }
    public int getFleeStatus() { return fleeStatus_; }
    
    // required int32 movingStatus = 12;
    public static final int MOVINGSTATUS_FIELD_NUMBER = 12;
    private boolean hasMovingStatus;
    private int movingStatus_ = 0;
    public boolean hasMovingStatus() { return hasMovingStatus; }
    public int getMovingStatus() { return movingStatus_; }
    
    // required int32 vehicleStatus = 13;
    public static final int VEHICLESTATUS_FIELD_NUMBER = 13;
    private boolean hasVehicleStatus;
    private int vehicleStatus_ = 0;
    public boolean hasVehicleStatus() { return hasVehicleStatus; }
    public int getVehicleStatus() { return vehicleStatus_; }
    
    // required string createdTime = 14;
    public static final int CREATEDTIME_FIELD_NUMBER = 14;
    private boolean hasCreatedTime;
    private java.lang.String createdTime_ = "";
    public boolean hasCreatedTime() { return hasCreatedTime; }
    public java.lang.String getCreatedTime() { return createdTime_; }
    
    // optional .Location location = 15;
    public static final int LOCATION_FIELD_NUMBER = 15;
    private boolean hasLocation;
    private cn.com.gps169.common.pb.VehiclePb.Location location_;
    public boolean hasLocation() { return hasLocation; }
    public cn.com.gps169.common.pb.VehiclePb.Location getLocation() { return location_; }
    
    // required int32 userId = 16;
    public static final int USERID_FIELD_NUMBER = 16;
    private boolean hasUserId;
    private int userId_ = 0;
    public boolean hasUserId() { return hasUserId; }
    public int getUserId() { return userId_; }
    
    private void initFields() {
      location_ = cn.com.gps169.common.pb.VehiclePb.Location.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasVehicleId) return false;
      if (!hasPlateNo) return false;
      if (!hasVin) return false;
      if (!hasEin) return false;
      if (!hasSimNo) return false;
      if (!hasTerminalNo) return false;
      if (!hasTerminalFlag) return false;
      if (!hasTerminalStatus) return false;
      if (!hasServiceStartTime) return false;
      if (!hasServiceEndTime) return false;
      if (!hasFleeStatus) return false;
      if (!hasMovingStatus) return false;
      if (!hasVehicleStatus) return false;
      if (!hasCreatedTime) return false;
      if (!hasUserId) return false;
      if (hasLocation()) {
        if (!getLocation().isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasVehicleId()) {
        output.writeInt32(1, getVehicleId());
      }
      if (hasPlateNo()) {
        output.writeString(2, getPlateNo());
      }
      if (hasVin()) {
        output.writeString(3, getVin());
      }
      if (hasEin()) {
        output.writeString(4, getEin());
      }
      if (hasSimNo()) {
        output.writeString(5, getSimNo());
      }
      if (hasTerminalNo()) {
        output.writeString(6, getTerminalNo());
      }
      if (hasTerminalFlag()) {
        output.writeInt32(7, getTerminalFlag());
      }
      if (hasTerminalStatus()) {
        output.writeInt32(8, getTerminalStatus());
      }
      if (hasServiceStartTime()) {
        output.writeString(9, getServiceStartTime());
      }
      if (hasServiceEndTime()) {
        output.writeString(10, getServiceEndTime());
      }
      if (hasFleeStatus()) {
        output.writeInt32(11, getFleeStatus());
      }
      if (hasMovingStatus()) {
        output.writeInt32(12, getMovingStatus());
      }
      if (hasVehicleStatus()) {
        output.writeInt32(13, getVehicleStatus());
      }
      if (hasCreatedTime()) {
        output.writeString(14, getCreatedTime());
      }
      if (hasLocation()) {
        output.writeMessage(15, getLocation());
      }
      if (hasUserId()) {
        output.writeInt32(16, getUserId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasVehicleId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getVehicleId());
      }
      if (hasPlateNo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPlateNo());
      }
      if (hasVin()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getVin());
      }
      if (hasEin()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getEin());
      }
      if (hasSimNo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getSimNo());
      }
      if (hasTerminalNo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getTerminalNo());
      }
      if (hasTerminalFlag()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, getTerminalFlag());
      }
      if (hasTerminalStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, getTerminalStatus());
      }
      if (hasServiceStartTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getServiceStartTime());
      }
      if (hasServiceEndTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getServiceEndTime());
      }
      if (hasFleeStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(11, getFleeStatus());
      }
      if (hasMovingStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, getMovingStatus());
      }
      if (hasVehicleStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(13, getVehicleStatus());
      }
      if (hasCreatedTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(14, getCreatedTime());
      }
      if (hasLocation()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getLocation());
      }
      if (hasUserId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, getUserId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static cn.com.gps169.common.pb.VehiclePb.Vehicle parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Vehicle parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Vehicle parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Vehicle parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Vehicle parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Vehicle parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Vehicle parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.com.gps169.common.pb.VehiclePb.Vehicle parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.com.gps169.common.pb.VehiclePb.Vehicle parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Vehicle parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.com.gps169.common.pb.VehiclePb.Vehicle prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private cn.com.gps169.common.pb.VehiclePb.Vehicle result;
      
      // Construct using cn.com.gps169.common.pb.VehiclePb.Vehicle.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new cn.com.gps169.common.pb.VehiclePb.Vehicle();
        return builder;
      }
      
      protected cn.com.gps169.common.pb.VehiclePb.Vehicle internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new cn.com.gps169.common.pb.VehiclePb.Vehicle();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.com.gps169.common.pb.VehiclePb.Vehicle.getDescriptor();
      }
      
      public cn.com.gps169.common.pb.VehiclePb.Vehicle getDefaultInstanceForType() {
        return cn.com.gps169.common.pb.VehiclePb.Vehicle.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public cn.com.gps169.common.pb.VehiclePb.Vehicle build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private cn.com.gps169.common.pb.VehiclePb.Vehicle buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public cn.com.gps169.common.pb.VehiclePb.Vehicle buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        cn.com.gps169.common.pb.VehiclePb.Vehicle returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.com.gps169.common.pb.VehiclePb.Vehicle) {
          return mergeFrom((cn.com.gps169.common.pb.VehiclePb.Vehicle)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.com.gps169.common.pb.VehiclePb.Vehicle other) {
        if (other == cn.com.gps169.common.pb.VehiclePb.Vehicle.getDefaultInstance()) return this;
        if (other.hasVehicleId()) {
          setVehicleId(other.getVehicleId());
        }
        if (other.hasPlateNo()) {
          setPlateNo(other.getPlateNo());
        }
        if (other.hasVin()) {
          setVin(other.getVin());
        }
        if (other.hasEin()) {
          setEin(other.getEin());
        }
        if (other.hasSimNo()) {
          setSimNo(other.getSimNo());
        }
        if (other.hasTerminalNo()) {
          setTerminalNo(other.getTerminalNo());
        }
        if (other.hasTerminalFlag()) {
          setTerminalFlag(other.getTerminalFlag());
        }
        if (other.hasTerminalStatus()) {
          setTerminalStatus(other.getTerminalStatus());
        }
        if (other.hasServiceStartTime()) {
          setServiceStartTime(other.getServiceStartTime());
        }
        if (other.hasServiceEndTime()) {
          setServiceEndTime(other.getServiceEndTime());
        }
        if (other.hasFleeStatus()) {
          setFleeStatus(other.getFleeStatus());
        }
        if (other.hasMovingStatus()) {
          setMovingStatus(other.getMovingStatus());
        }
        if (other.hasVehicleStatus()) {
          setVehicleStatus(other.getVehicleStatus());
        }
        if (other.hasCreatedTime()) {
          setCreatedTime(other.getCreatedTime());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setVehicleId(input.readInt32());
              break;
            }
            case 18: {
              setPlateNo(input.readString());
              break;
            }
            case 26: {
              setVin(input.readString());
              break;
            }
            case 34: {
              setEin(input.readString());
              break;
            }
            case 42: {
              setSimNo(input.readString());
              break;
            }
            case 50: {
              setTerminalNo(input.readString());
              break;
            }
            case 56: {
              setTerminalFlag(input.readInt32());
              break;
            }
            case 64: {
              setTerminalStatus(input.readInt32());
              break;
            }
            case 74: {
              setServiceStartTime(input.readString());
              break;
            }
            case 82: {
              setServiceEndTime(input.readString());
              break;
            }
            case 88: {
              setFleeStatus(input.readInt32());
              break;
            }
            case 96: {
              setMovingStatus(input.readInt32());
              break;
            }
            case 104: {
              setVehicleStatus(input.readInt32());
              break;
            }
            case 114: {
              setCreatedTime(input.readString());
              break;
            }
            case 122: {
              cn.com.gps169.common.pb.VehiclePb.Location.Builder subBuilder = cn.com.gps169.common.pb.VehiclePb.Location.newBuilder();
              if (hasLocation()) {
                subBuilder.mergeFrom(getLocation());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLocation(subBuilder.buildPartial());
              break;
            }
            case 128: {
              setUserId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // required int32 vehicleId = 1;
      public boolean hasVehicleId() {
        return result.hasVehicleId();
      }
      public int getVehicleId() {
        return result.getVehicleId();
      }
      public Builder setVehicleId(int value) {
        result.hasVehicleId = true;
        result.vehicleId_ = value;
        return this;
      }
      public Builder clearVehicleId() {
        result.hasVehicleId = false;
        result.vehicleId_ = 0;
        return this;
      }
      
      // required string plateNo = 2;
      public boolean hasPlateNo() {
        return result.hasPlateNo();
      }
      public java.lang.String getPlateNo() {
        return result.getPlateNo();
      }
      public Builder setPlateNo(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPlateNo = true;
        result.plateNo_ = value;
        return this;
      }
      public Builder clearPlateNo() {
        result.hasPlateNo = false;
        result.plateNo_ = getDefaultInstance().getPlateNo();
        return this;
      }
      
      // required string vin = 3;
      public boolean hasVin() {
        return result.hasVin();
      }
      public java.lang.String getVin() {
        return result.getVin();
      }
      public Builder setVin(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasVin = true;
        result.vin_ = value;
        return this;
      }
      public Builder clearVin() {
        result.hasVin = false;
        result.vin_ = getDefaultInstance().getVin();
        return this;
      }
      
      // required string ein = 4;
      public boolean hasEin() {
        return result.hasEin();
      }
      public java.lang.String getEin() {
        return result.getEin();
      }
      public Builder setEin(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEin = true;
        result.ein_ = value;
        return this;
      }
      public Builder clearEin() {
        result.hasEin = false;
        result.ein_ = getDefaultInstance().getEin();
        return this;
      }
      
      // required string simNo = 5;
      public boolean hasSimNo() {
        return result.hasSimNo();
      }
      public java.lang.String getSimNo() {
        return result.getSimNo();
      }
      public Builder setSimNo(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSimNo = true;
        result.simNo_ = value;
        return this;
      }
      public Builder clearSimNo() {
        result.hasSimNo = false;
        result.simNo_ = getDefaultInstance().getSimNo();
        return this;
      }
      
      // required string terminalNo = 6;
      public boolean hasTerminalNo() {
        return result.hasTerminalNo();
      }
      public java.lang.String getTerminalNo() {
        return result.getTerminalNo();
      }
      public Builder setTerminalNo(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTerminalNo = true;
        result.terminalNo_ = value;
        return this;
      }
      public Builder clearTerminalNo() {
        result.hasTerminalNo = false;
        result.terminalNo_ = getDefaultInstance().getTerminalNo();
        return this;
      }
      
      // required int32 terminalFlag = 7;
      public boolean hasTerminalFlag() {
        return result.hasTerminalFlag();
      }
      public int getTerminalFlag() {
        return result.getTerminalFlag();
      }
      public Builder setTerminalFlag(int value) {
        result.hasTerminalFlag = true;
        result.terminalFlag_ = value;
        return this;
      }
      public Builder clearTerminalFlag() {
        result.hasTerminalFlag = false;
        result.terminalFlag_ = 0;
        return this;
      }
      
      // required int32 terminal_status = 8;
      public boolean hasTerminalStatus() {
        return result.hasTerminalStatus();
      }
      public int getTerminalStatus() {
        return result.getTerminalStatus();
      }
      public Builder setTerminalStatus(int value) {
        result.hasTerminalStatus = true;
        result.terminalStatus_ = value;
        return this;
      }
      public Builder clearTerminalStatus() {
        result.hasTerminalStatus = false;
        result.terminalStatus_ = 0;
        return this;
      }
      
      // required string serviceStartTime = 9;
      public boolean hasServiceStartTime() {
        return result.hasServiceStartTime();
      }
      public java.lang.String getServiceStartTime() {
        return result.getServiceStartTime();
      }
      public Builder setServiceStartTime(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasServiceStartTime = true;
        result.serviceStartTime_ = value;
        return this;
      }
      public Builder clearServiceStartTime() {
        result.hasServiceStartTime = false;
        result.serviceStartTime_ = getDefaultInstance().getServiceStartTime();
        return this;
      }
      
      // required string serviceEndTime = 10;
      public boolean hasServiceEndTime() {
        return result.hasServiceEndTime();
      }
      public java.lang.String getServiceEndTime() {
        return result.getServiceEndTime();
      }
      public Builder setServiceEndTime(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasServiceEndTime = true;
        result.serviceEndTime_ = value;
        return this;
      }
      public Builder clearServiceEndTime() {
        result.hasServiceEndTime = false;
        result.serviceEndTime_ = getDefaultInstance().getServiceEndTime();
        return this;
      }
      
      // required int32 fleeStatus = 11;
      public boolean hasFleeStatus() {
        return result.hasFleeStatus();
      }
      public int getFleeStatus() {
        return result.getFleeStatus();
      }
      public Builder setFleeStatus(int value) {
        result.hasFleeStatus = true;
        result.fleeStatus_ = value;
        return this;
      }
      public Builder clearFleeStatus() {
        result.hasFleeStatus = false;
        result.fleeStatus_ = 0;
        return this;
      }
      
      // required int32 movingStatus = 12;
      public boolean hasMovingStatus() {
        return result.hasMovingStatus();
      }
      public int getMovingStatus() {
        return result.getMovingStatus();
      }
      public Builder setMovingStatus(int value) {
        result.hasMovingStatus = true;
        result.movingStatus_ = value;
        return this;
      }
      public Builder clearMovingStatus() {
        result.hasMovingStatus = false;
        result.movingStatus_ = 0;
        return this;
      }
      
      // required int32 vehicleStatus = 13;
      public boolean hasVehicleStatus() {
        return result.hasVehicleStatus();
      }
      public int getVehicleStatus() {
        return result.getVehicleStatus();
      }
      public Builder setVehicleStatus(int value) {
        result.hasVehicleStatus = true;
        result.vehicleStatus_ = value;
        return this;
      }
      public Builder clearVehicleStatus() {
        result.hasVehicleStatus = false;
        result.vehicleStatus_ = 0;
        return this;
      }
      
      // required string createdTime = 14;
      public boolean hasCreatedTime() {
        return result.hasCreatedTime();
      }
      public java.lang.String getCreatedTime() {
        return result.getCreatedTime();
      }
      public Builder setCreatedTime(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCreatedTime = true;
        result.createdTime_ = value;
        return this;
      }
      public Builder clearCreatedTime() {
        result.hasCreatedTime = false;
        result.createdTime_ = getDefaultInstance().getCreatedTime();
        return this;
      }
      
      // optional .Location location = 15;
      public boolean hasLocation() {
        return result.hasLocation();
      }
      public cn.com.gps169.common.pb.VehiclePb.Location getLocation() {
        return result.getLocation();
      }
      public Builder setLocation(cn.com.gps169.common.pb.VehiclePb.Location value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLocation = true;
        result.location_ = value;
        return this;
      }
      public Builder setLocation(cn.com.gps169.common.pb.VehiclePb.Location.Builder builderForValue) {
        result.hasLocation = true;
        result.location_ = builderForValue.build();
        return this;
      }
      public Builder mergeLocation(cn.com.gps169.common.pb.VehiclePb.Location value) {
        if (result.hasLocation() &&
            result.location_ != cn.com.gps169.common.pb.VehiclePb.Location.getDefaultInstance()) {
          result.location_ =
            cn.com.gps169.common.pb.VehiclePb.Location.newBuilder(result.location_).mergeFrom(value).buildPartial();
        } else {
          result.location_ = value;
        }
        result.hasLocation = true;
        return this;
      }
      public Builder clearLocation() {
        result.hasLocation = false;
        result.location_ = cn.com.gps169.common.pb.VehiclePb.Location.getDefaultInstance();
        return this;
      }
      
      // required int32 userId = 16;
      public boolean hasUserId() {
        return result.hasUserId();
      }
      public int getUserId() {
        return result.getUserId();
      }
      public Builder setUserId(int value) {
        result.hasUserId = true;
        result.userId_ = value;
        return this;
      }
      public Builder clearUserId() {
        result.hasUserId = false;
        result.userId_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Vehicle)
    }
    
    static {
      defaultInstance = new Vehicle(true);
      cn.com.gps169.common.pb.VehiclePb.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Vehicle)
  }
  
  public static final class Location extends
      com.google.protobuf.GeneratedMessage {
    // Use Location.newBuilder() to construct.
    private Location() {
      initFields();
    }
    private Location(boolean noInit) {}
    
    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }
    
    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cn.com.gps169.common.pb.VehiclePb.internal_static_Location_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cn.com.gps169.common.pb.VehiclePb.internal_static_Location_fieldAccessorTable;
    }
    
    // required string longitude = 1;
    public static final int LONGITUDE_FIELD_NUMBER = 1;
    private boolean hasLongitude;
    private java.lang.String longitude_ = "";
    public boolean hasLongitude() { return hasLongitude; }
    public java.lang.String getLongitude() { return longitude_; }
    
    // required string latitude = 2;
    public static final int LATITUDE_FIELD_NUMBER = 2;
    private boolean hasLatitude;
    private java.lang.String latitude_ = "";
    public boolean hasLatitude() { return hasLatitude; }
    public java.lang.String getLatitude() { return latitude_; }
    
    // required string address = 3;
    public static final int ADDRESS_FIELD_NUMBER = 3;
    private boolean hasAddress;
    private java.lang.String address_ = "";
    public boolean hasAddress() { return hasAddress; }
    public java.lang.String getAddress() { return address_; }
    
    // required float altitude = 4;
    public static final int ALTITUDE_FIELD_NUMBER = 4;
    private boolean hasAltitude;
    private float altitude_ = 0F;
    public boolean hasAltitude() { return hasAltitude; }
    public float getAltitude() { return altitude_; }
    
    // required float speed = 5;
    public static final int SPEED_FIELD_NUMBER = 5;
    private boolean hasSpeed;
    private float speed_ = 0F;
    public boolean hasSpeed() { return hasSpeed; }
    public float getSpeed() { return speed_; }
    
    // required string lastUploadTime = 6;
    public static final int LASTUPLOADTIME_FIELD_NUMBER = 6;
    private boolean hasLastUploadTime;
    private java.lang.String lastUploadTime_ = "";
    public boolean hasLastUploadTime() { return hasLastUploadTime; }
    public java.lang.String getLastUploadTime() { return lastUploadTime_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasLongitude) return false;
      if (!hasLatitude) return false;
      if (!hasAddress) return false;
      if (!hasAltitude) return false;
      if (!hasSpeed) return false;
      if (!hasLastUploadTime) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasLongitude()) {
        output.writeString(1, getLongitude());
      }
      if (hasLatitude()) {
        output.writeString(2, getLatitude());
      }
      if (hasAddress()) {
        output.writeString(3, getAddress());
      }
      if (hasAltitude()) {
        output.writeFloat(4, getAltitude());
      }
      if (hasSpeed()) {
        output.writeFloat(5, getSpeed());
      }
      if (hasLastUploadTime()) {
        output.writeString(6, getLastUploadTime());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasLongitude()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getLongitude());
      }
      if (hasLatitude()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getLatitude());
      }
      if (hasAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getAddress());
      }
      if (hasAltitude()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, getAltitude());
      }
      if (hasSpeed()) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, getSpeed());
      }
      if (hasLastUploadTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getLastUploadTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static cn.com.gps169.common.pb.VehiclePb.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.com.gps169.common.pb.VehiclePb.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static cn.com.gps169.common.pb.VehiclePb.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static cn.com.gps169.common.pb.VehiclePb.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cn.com.gps169.common.pb.VehiclePb.Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private cn.com.gps169.common.pb.VehiclePb.Location result;
      
      // Construct using cn.com.gps169.common.pb.VehiclePb.Location.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new cn.com.gps169.common.pb.VehiclePb.Location();
        return builder;
      }
      
      protected cn.com.gps169.common.pb.VehiclePb.Location internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new cn.com.gps169.common.pb.VehiclePb.Location();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cn.com.gps169.common.pb.VehiclePb.Location.getDescriptor();
      }
      
      public cn.com.gps169.common.pb.VehiclePb.Location getDefaultInstanceForType() {
        return cn.com.gps169.common.pb.VehiclePb.Location.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public cn.com.gps169.common.pb.VehiclePb.Location build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private cn.com.gps169.common.pb.VehiclePb.Location buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public cn.com.gps169.common.pb.VehiclePb.Location buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        cn.com.gps169.common.pb.VehiclePb.Location returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cn.com.gps169.common.pb.VehiclePb.Location) {
          return mergeFrom((cn.com.gps169.common.pb.VehiclePb.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(cn.com.gps169.common.pb.VehiclePb.Location other) {
        if (other == cn.com.gps169.common.pb.VehiclePb.Location.getDefaultInstance()) return this;
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasAddress()) {
          setAddress(other.getAddress());
        }
        if (other.hasAltitude()) {
          setAltitude(other.getAltitude());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasLastUploadTime()) {
          setLastUploadTime(other.getLastUploadTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setLongitude(input.readString());
              break;
            }
            case 18: {
              setLatitude(input.readString());
              break;
            }
            case 26: {
              setAddress(input.readString());
              break;
            }
            case 37: {
              setAltitude(input.readFloat());
              break;
            }
            case 45: {
              setSpeed(input.readFloat());
              break;
            }
            case 50: {
              setLastUploadTime(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string longitude = 1;
      public boolean hasLongitude() {
        return result.hasLongitude();
      }
      public java.lang.String getLongitude() {
        return result.getLongitude();
      }
      public Builder setLongitude(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLongitude = true;
        result.longitude_ = value;
        return this;
      }
      public Builder clearLongitude() {
        result.hasLongitude = false;
        result.longitude_ = getDefaultInstance().getLongitude();
        return this;
      }
      
      // required string latitude = 2;
      public boolean hasLatitude() {
        return result.hasLatitude();
      }
      public java.lang.String getLatitude() {
        return result.getLatitude();
      }
      public Builder setLatitude(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLatitude = true;
        result.latitude_ = value;
        return this;
      }
      public Builder clearLatitude() {
        result.hasLatitude = false;
        result.latitude_ = getDefaultInstance().getLatitude();
        return this;
      }
      
      // required string address = 3;
      public boolean hasAddress() {
        return result.hasAddress();
      }
      public java.lang.String getAddress() {
        return result.getAddress();
      }
      public Builder setAddress(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAddress = true;
        result.address_ = value;
        return this;
      }
      public Builder clearAddress() {
        result.hasAddress = false;
        result.address_ = getDefaultInstance().getAddress();
        return this;
      }
      
      // required float altitude = 4;
      public boolean hasAltitude() {
        return result.hasAltitude();
      }
      public float getAltitude() {
        return result.getAltitude();
      }
      public Builder setAltitude(float value) {
        result.hasAltitude = true;
        result.altitude_ = value;
        return this;
      }
      public Builder clearAltitude() {
        result.hasAltitude = false;
        result.altitude_ = 0F;
        return this;
      }
      
      // required float speed = 5;
      public boolean hasSpeed() {
        return result.hasSpeed();
      }
      public float getSpeed() {
        return result.getSpeed();
      }
      public Builder setSpeed(float value) {
        result.hasSpeed = true;
        result.speed_ = value;
        return this;
      }
      public Builder clearSpeed() {
        result.hasSpeed = false;
        result.speed_ = 0F;
        return this;
      }
      
      // required string lastUploadTime = 6;
      public boolean hasLastUploadTime() {
        return result.hasLastUploadTime();
      }
      public java.lang.String getLastUploadTime() {
        return result.getLastUploadTime();
      }
      public Builder setLastUploadTime(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLastUploadTime = true;
        result.lastUploadTime_ = value;
        return this;
      }
      public Builder clearLastUploadTime() {
        result.hasLastUploadTime = false;
        result.lastUploadTime_ = getDefaultInstance().getLastUploadTime();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Location)
    }
    
    static {
      defaultInstance = new Location(true);
      cn.com.gps169.common.pb.VehiclePb.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Location)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Vehicle_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Vehicle_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Location_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026protos/vehiclePb.proto\"\316\002\n\007Vehicle\022\021\n\t" +
      "vehicleId\030\001 \002(\005\022\017\n\007plateNo\030\002 \002(\t\022\013\n\003vin\030" +
      "\003 \002(\t\022\013\n\003ein\030\004 \002(\t\022\r\n\005simNo\030\005 \002(\t\022\022\n\nter" +
      "minalNo\030\006 \002(\t\022\024\n\014terminalFlag\030\007 \002(\005\022\027\n\017t" +
      "erminal_status\030\010 \002(\005\022\030\n\020serviceStartTime" +
      "\030\t \002(\t\022\026\n\016serviceEndTime\030\n \002(\t\022\022\n\nfleeSt" +
      "atus\030\013 \002(\005\022\024\n\014movingStatus\030\014 \002(\005\022\025\n\rvehi" +
      "cleStatus\030\r \002(\005\022\023\n\013createdTime\030\016 \002(\t\022\033\n\010" +
      "location\030\017 \001(\0132\t.Location\022\016\n\006userId\030\020 \002(" +
      "\005\"y\n\010Location\022\021\n\tlongitude\030\001 \002(\t\022\020\n\010lati",
      "tude\030\002 \002(\t\022\017\n\007address\030\003 \002(\t\022\020\n\010altitude\030" +
      "\004 \002(\002\022\r\n\005speed\030\005 \002(\002\022\026\n\016lastUploadTime\030\006" +
      " \002(\tB\031\n\027cn.com.gps169.common.pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Vehicle_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Vehicle_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Vehicle_descriptor,
              new java.lang.String[] { "VehicleId", "PlateNo", "Vin", "Ein", "SimNo", "TerminalNo", "TerminalFlag", "TerminalStatus", "ServiceStartTime", "ServiceEndTime", "FleeStatus", "MovingStatus", "VehicleStatus", "CreatedTime", "Location", "UserId", },
              cn.com.gps169.common.pb.VehiclePb.Vehicle.class,
              cn.com.gps169.common.pb.VehiclePb.Vehicle.Builder.class);
          internal_static_Location_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Location_descriptor,
              new java.lang.String[] { "Longitude", "Latitude", "Address", "Altitude", "Speed", "LastUploadTime", },
              cn.com.gps169.common.pb.VehiclePb.Location.class,
              cn.com.gps169.common.pb.VehiclePb.Location.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
